name:                oci-haskell-sdk
version:             0.1.0.0
github:              "owainlewis/oci-hs-sdk"
license:             BSD3
author:              "Owain Lewis"
maintainer:          "Owain Lewis <owain.lewis@oracle.com>"
copyright:           "2018 Owain Lewis"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on Github at <https://github.com/owainlewis/oci-haskell-sdk#readme>
dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  oci-hs-sdk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oci-haskell-sdk
